/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 kfo_case_b4.glb -o kfo_case_1.tsx -t -k -K --shadows -S
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useFrame, Vector3 } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { DoubleSide } from 'three'
import { useSpring, animated } from '@react-spring/three'

type GLTFResult = GLTF & {
  nodes: {
    xz_plane: THREE.Mesh
    yz_plane: THREE.Mesh
    xy_plane: THREE.Mesh
    OK: THREE.Mesh
    UK: THREE.Mesh
  }
  materials: {}
}

type KieferProps = JSX.IntrinsicElements['group'] & {
  okVisible: boolean,
  ukVisible: boolean,
  semi: boolean,
  rulerMode: boolean,
  setMeasurement: (e: any) => void,
  axis: 'x' | 'y' | 'z' | null
}

const Model = (props: KieferProps) => {
  const { nodes } = useGLTF('kfo_case_b4.glb') as GLTFResult
  const { okOpacity } = useSpring({ okOpacity: props.semi ? 0.5 : props.okVisible ? 1 : 0 })
  const { ukOpacity } = useSpring({ ukOpacity: props.semi ? 0.5 : props.ukVisible ? 1 : 0 })
  const visible = new THREE.MeshBasicMaterial({ visible: true, side: DoubleSide })
  const invisible = new THREE.MeshBasicMaterial({ visible: false, side: DoubleSide })
  const okMatRef = useRef<THREE.MeshStandardMaterial>(null!)
  const ukMatRef = useRef<THREE.MeshStandardMaterial>(null!)
  useFrame(() => {
    okMatRef.current.opacity = okOpacity.get()
    ukMatRef.current.opacity = ukOpacity.get()
  })
  const sendMeasurement = (e: any) => {
    if (props.rulerMode) {
      props.setMeasurement(e)
    }
  }
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="camera_bottom_position" position={[0, -500, 0]} />
        <group name="camera_frontal_position" position={[0, 0, 500]} />
        <group name="camera_left_position" position={[-500, 0, 0]} />
        <group name="camera_right_position" position={[500, 0, 0]} />
        <group name="camera_top_position" position={[0, 500, 0]} />

        <mesh name="yz_plane" geometry={nodes.yz_plane.geometry}
	      material={invisible}
	      onClick={(e) => props.axis == "x" ? sendMeasurement(e) : null}/>
        <mesh name="xy_plane" geometry={nodes.xy_plane.geometry}
	      material={invisible}
	      onClick={(e) => props.axis == "y" ? sendMeasurement(e) : null}/>
        <mesh name="xz_plane" geometry={nodes.xz_plane.geometry}
	      material={invisible}
	      onClick={(e) => props.axis == "z" ? sendMeasurement(e) : null}/>

	<animated.mesh name="OK" castShadow receiveShadow
		       geometry={nodes.OK.geometry}
		       onClick={(e) => props.okVisible && !props.axis ? sendMeasurement(e) : null}>
	    <meshStandardMaterial ref={okMatRef} transparent color="#E7E7E7" />
	</animated.mesh>
	<animated.mesh name="UK" castShadow receiveShadow
		       geometry={nodes.UK.geometry}
		       onClick={(e) => props.ukVisible && !props.axis ? sendMeasurement(e) : null}>
	    <meshStandardMaterial ref={ukMatRef} transparent color="#E7E7E7" />
	</animated.mesh>
      </group>
    </group>
  )
}

export default Model

useGLTF.preload('kfo_case_b4.glb')
