/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 kfo_case_1.gltf -o kfo_case_1.tsx -t -k -K --shadows -S
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useFrame, Vector3 } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { DoubleSide } from "three";
import { useSpring, animated } from "@react-spring/three";
import MeshFresnelMaterial from "./MeshFresnelMaterial.jsx";

type GLTFResult = GLTF & {
  nodes: {
    xz_plane: THREE.Mesh;
    yz_plane: THREE.Mesh;
    xy_plane: THREE.Mesh;
    OK: THREE.Mesh;
    UK: THREE.Mesh;
  };
  materials: {};
};

type KieferProps = JSX.IntrinsicElements["group"] & {
  okVisible: boolean;
  ukVisible: boolean;
  semi: boolean;
  rulerMode: boolean;
  setMeasurement: (e: any) => void;
  axis: "x" | "y" | "z" | null;
};

const Model = (props: KieferProps) => {
  const { nodes } = useGLTF("/public/model.glb") as GLTFResult;
  const { okOpacity } = useSpring({
    okOpacity: props.semi ? 0.5 : props.okVisible ? 1 : 0,
  });
  const { ukOpacity } = useSpring({
    ukOpacity: props.semi ? 0.5 : props.ukVisible ? 1 : 0,
  });
  const visible = new THREE.MeshBasicMaterial({
    visible: true,
    side: DoubleSide,
  });
  const invisible = new THREE.MeshBasicMaterial({
    visible: false,
    side: DoubleSide,
  });
  const okMatRef = useRef<THREE.MeshStandardMaterial>(null!);
  const ukMatRef = useRef<THREE.MeshStandardMaterial>(null!);

  const sendMeasurement = (e: any) => {
    props.setMeasurement(e);
  };
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="camera_bottom_position" position={[0, -500, 0]} />
        <group name="camera_frontal_position" position={[0, 0, 500]} />
        <group name="camera_left_position" position={[-500, 0, 0]} />
        <group name="camera_right_position" position={[500, 0, 0]} />
        <group name="camera_top_position" position={[0, 500, 0]} />

        {props.okVisible && (
          <animated.mesh
            name="OK"
            castShadow
            receiveShadow
            geometry={nodes.OK.geometry}
            onDoubleClick={(e) =>
              props.okVisible ? sendMeasurement(e) : null
            }
          >
            <MeshFresnelMaterial
              fresnelColor={"#ffffff"}
              baseColor={"#cccccc"}
              amount={0.6}
              offset={0.025}
              intensity={1.2}
              fresnelAlpha={1}
              alpha={props.semi}
            />
          </animated.mesh>
        )}
        {props.ukVisible && (
          <animated.mesh
            name="UK"
            castShadow
            receiveShadow
            geometry={nodes.UK.geometry}
            onDoubleClick={(e) =>
              props.ukVisible ? sendMeasurement(e) : null
            }
          >
            <MeshFresnelMaterial
              fresnelColor={"#ffffff"}
              baseColor={"#cccccc"}
              amount={0.6}
              offset={0.025}
              intensity={1.2}
              fresnelAlpha={1}
              alpha={props.semi}
            />
          </animated.mesh>
        )}
      </group>
    </group>
  );
};

export default Model;

useGLTF.preload("/public/model.glb");
